version: '3'
services:
  laravel:
    build:
      context: ./laravel-app/
    ports:
      - 8000:5001
    volumes:
      - ./laravel-app:/var/www/html
    networks:
      - devnetwork
  flask: 
    build:
      context: ./flask-app/
    ports:
      - 5000:5000
    volumes:
      - ./flask-app:/app
    networks:
      - devnetwork
  react:
    build:
      context: ./react-app
    ports:
      - 3000:80
    volumes:
      - ./react-app:/app
    networks:
      - devnetwork
networks:
  devnetwork: