version: '3'
services:
  laravel:
    build:
      context: ./laravel-app/
    ports:
      - 8001:8000
    volumes:
      - ./laravel-app:/var/www/html
    networks:
      - prodnetwork
  flask: 
    build:
      context: ./flask-app/
    ports:
      - 5001:5000
    volumes:
      - ./flask-app:/app
    networks:
      - prodnetwork
  react:
    build:
      context: ./react-app
    ports:
      - 3001:80
    volumes:
      - ./react-app:/app
    networks:
      - prodnetwork
networks:
  prodnetwork: